version: '3.8'

services:
  libraryit-server:
    build: .
    container_name: libraryit-server
    ports:
      - "1445:445"
      - "1139:139"
    volumes:
      - ./data:/libraryit
      - ./logs:/logs
    restart: unless-stopped

  libraryit-logger:
    image: alpine
    container_name: libraryit-logger
    depends_on:
      - libraryit-server
    volumes:
      - ./logs:/logs
    command: tail -f /logs/libraryit.log
    restart: unless-stopped