[global]
    workgroup = WORKGROUP
    server string = LibraryIT Server
    security = user
    map to guest = bad user
    passdb backend = tdbsam
    access based share enum = yes

[ebooks]
    path = /libraryit/ebooks
    valid users = @staff, @readonly
    write list = @staff
    read list = @readonly
    browseable = yes
    guest ok = no
    vfs objects = full_audit
    full_audit:prefix = %u|%S
    full_audit:success = connect open
    full_audit:failure = connect open
    full_audit:facility = local5
    full_audit:priority = notice

[papers]
    path = /libraryit/papers
    valid users = @staff, @readonly
    write list = @staff
    read list = @readonly
    browseable = yes
    guest ok = no
    vfs objects = full_audit
    full_audit:prefix = %u|%S
    full_audit:success = connect open
    full_audit:failure = connect open
    full_audit:facility = local5
    full_audit:priority = notice

[sourcecode]
    path = /libraryit/sourcecode
    valid users = @staff, @readonly
    write list = @staff
    browseable = yes
    guest ok = no
    vfs objects = full_audit
    full_audit:prefix = %u|%S
    full_audit:success = connect open
    full_audit:failure = connect open
    full_audit:facility = local5
    full_audit:priority = notice

[docs]
    path = /libraryit/docs
    valid users = @staff, @readonly
    write list = librarian
    read list = @staff, @readonly
    browseable = yes
    guest ok = no
    vfs objects = full_audit
    full_audit:prefix = %u|%S
    full_audit:success = connect open
    full_audit:failure = connect open
    full_audit:facility = local5
    full_audit:priority = notice